### PR TITLE
Fixed some systems logos for visibility

### PR DESCRIPTION
**Pull request by PhillBenoit**

### CODE REVIEW

**Comment by cmitu** [comment]
Hello and thank you for the changes. 
I see you also changed some previous logos (PS3/Thomsom MO-TO/Steam), can you please keep them in place and change only the color ?
I don't see the issue with the MSX logo though, it seems to load fine for me. What system/OS are you using ?

**Comment by PhillBenoit** [comment]
I'm just learning how SVG files work.

- I'll give moto another shot.
- The original Steam logo didn't allow me to apply the gradient pattern so I had to swap it out.  I think I can still use my logo with the original font if I mess with it enough.
- PS3 needs the replacement.  The original does not look right at all.  That being said, I ran it through a program but I think I can do it by hand better.
- For MSX, any time Github tries to render the original file, it errors out.  (Chrome and Firefox)  I've been using Visual Studio for version control and I haven't bothered to stop it from forcing me to use Edge to render the image.  Even the raw file does not load there.  As long as I'm going back through stuff, I'll see if I can fix the original.

**Comment by cmitu** [comment]
> * For MSX, any time Github tries to render the original file, it errors out.  (Chrome and Firefox)  I've been using Visual Studio for version control and I haven't bothered to stop it from forcing me to use Edge to render the image.  Even the raw file does not load there.  As long as I'm going back through stuff, I'll see if I can fix the original.

I wasn't referring to Github, is there an issue in EmulationStation ? I can see the logo fine for the MSX system using this theme.

**Comment by PhillBenoit** [comment]
This all started with me adding NAOMI to my own system.  Once I got that working, I went about trying to fix Game and Watch.  After I fixed that, I decided to try and publish that change.  I figured as long as I was in the original repository, I would look for other oversights.  I don't use any of the systems I modified but I noticed MSX broke the github UI and the other systems had the same color problem as Game and Watch.  Once I got all that done I set up my fork.

I made the changes previously mentioned and pushed a new commit.
- I found the problem in msx.  One of the SVG elements tried to use a namespace that was not declared.  I took it out.
- moto, ps3, and steam I redid based off of everything I have learned so far
- I added my NAOMI stuff.  Once this gets merged, I'll pull emulationstation and add NAOMI to es_systems.cfg

**Comment by cmitu** [comment]
Sorry, I should have been clearer previously - no changed to the logos please, I'd like to keep them as submitted by the theme author. From the changes proposed, I'd like to keep:

 * the MSX logo has no issues in EmulationStation, but if it makes it work better in Github, then that's ok. Include the change as a separate PR
 * the Naomi logo I guess is ok - also include it as a separate PR
 * G & W and X68000 logo color changes,in a separate PR (both can be included).

 The rest should not be included or - if you intend to changee it so it fixes the color - please use their exsint form. Leave aside the MO TO system, I'll redo it myself. Having separate PR/commits for the changes will allow to cherry pick the changes to the other 2 branches used (_centered_ and _nometa_).

 Thank you.

**Pull request closed without merging**
