### PR TITLE
add naomi

### PR DESCRIPTION
**Pull request by PhillBenoit**

### CODE REVIEW

**Comment by cmitu** [comment]
The system image is ok, but isn't the controller from a [Sega Astro City](https://segaretro.org/Astro_City) cabinet ?

**Comment by PhillBenoit** [comment]
Yes.  While not exclusively, a lot of NAOMI systems make their homes in those machines.  There is not a single form factor to conform to so I chose the most common.

**Comment by cmitu** [comment]
If there's no specific Naomi controller setup, then please use the existing 'arcade' image.

**Comment by PhillBenoit** [comment]
The existing arcade image is not accurate.  Very few of the games use 6 buttons.  The lower half comes from the existing image.  I can leave out the Astro City stuff if you want.

**Comment by cmitu** [comment]
> I can leave out the Astro City stuff if you want.

That would work also, thanks.

**Comment by PhillBenoit** [comment]
that should do it

**Comment by cmitu** [comment]
I guess it's ok. Thanks for the changes.

**Pull request merged**
